config/routes.rb
Rails.application.routes.draw do
  resources :singers

  root 'singers#index'

end

app/models/singer.rb
class Singer < ActiveRecord::Base

  def words_count
    words = self.lyrics.gsub(/\,|\.+|\!|\?|\"/, '').split(' ')
    frequency = Hash.new(0)
    words.each { |word| frequency[word.downcase] += 1 if word.length > 3}
    word_list = []
    frequency.each do |key, value| 
      obj = {text: key, weight: value}
      word_list << obj if value > 1
    end
    return word_list
  end

  def self.search(term)
    where('LOWER(name) LIKE :term', term: "%#{term.downcase}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: [:show, :edit, :update, :destroy]

  # GET /singers
  # GET /singers.json
  def index
    @singers = Singer.all
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
    @words_count = @singer.words_count
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit
  end

  # POST /singers
  # POST /singers.json
  def create
    params[:singer][:lyrics] = params[:singer][:lyrics].squish
    @singer = Singer.new(singer_params)

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1
  # PATCH/PUT /singers/1.json
  def update
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to @singer, notice: 'Singer was successfully updated.' }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    @singer.destroy
    respond_to do |format|
      format.html { redirect_to singers_url, notice: 'Singer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def singer_params
      params.require(:singer).permit(:name, :lyrics)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Singer Cloud" %></title>
    <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

    <%= yield %>

  </body>
</html>

app/views/singers/_form.html.erb
<%= form_for(@singer) do |f| %>
  <% if @singer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
      <% @singer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics, style: "height: 300px" %>
  </div>
  <div class="actions">
    <%= f.submit 'Salva', class: 'button secondary' %>
  </div>
<% end %>

app/views/singers/edit.html.erb
<div class="row">
  <div class="large-24">
    <h1>Editing Singer</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @singer, class: 'button secondary small'%>
    <%= link_to 'Back', singers_path, class: 'button secondary small' %>
  </div>
</div>

app/views/singers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="large-24 center">
    <h1 class="home_title">
      <%= link_to 'Cantanti', root_path %>
    </h1>
    
    <ul id="singers_list">
      <% @singers.each do |singer| %>
        <li>
          <%= link_to singer.name, singer %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/singers/new.html.erb
<div class="row">
  <div class="large-24">
    <h1>New Singer</h1>

    <%= render 'form' %>

    <%= link_to 'Back', singers_path, class: 'button secondary small' %>

  </div>
</div>

app/views/singers/show.html.erb
<div class="row">
  <div class="large-24">
    <%= link_to image_tag('sc_logo_black.png'), root_path, class: 'inner-logo' %>
  </div>
</div>
<div class="row">
  <div class="large-24">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<div id="wordcloud" style="width: 1200px; height: 500px; position: relative;"></div>
<div class="row">
  <div class="large-24 center">
    <h2><%= @singer.name %></h2>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#wordcloud").jQCloud(<%= raw @words_count.to_json %>);
  });
</script>